[package]
name = "params"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>", "conscio <julian.konchunas@gmail.com>"]

[dependencies]
lazy_static = "0.2"
chain = { path = "../chain" }
primitives = { path = "../primitives" }
